# Project Name
TARGET = TFT_TEST

# Sources
CPP_SOURCES = TFT_TEST.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

C_INCLUDES += \
-I. \
-Iili9341_ui_driver \ 

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
